package com.leafcode.petmint.locationSelector

import android.content.Context
import android.content.SharedPreferences
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.activityViewModels
import androidx.navigation.fragment.findNavController
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.leafcode.petmint.R
import com.leafcode.petmint.databinding.FragmentStateSelectorBinding

//Fragment to select state
class StateSelectorFragment : Fragment() {

    //ViewModel of the activity of this fragment
    val activityViewModel : LocationSelectorViewModel by activityViewModels()

    //Objects for recycler view
    private lateinit var recyclerView : RecyclerView
    private lateinit var layoutManager : RecyclerView.LayoutManager

    //Object of shared preference
    private lateinit var sharedPreferences: SharedPreferences

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        val binding : FragmentStateSelectorBinding = FragmentStateSelectorBinding.inflate(inflater,container,false)

        //Updating the title of the action bar
        activityViewModel.updateActionBarTitle("Select State")

        //Initialising the shared preferences of the location
        sharedPreferences = this.requireActivity().getSharedPreferences(getString(R.string.location_preferences),
            Context.MODE_PRIVATE)
        
        val inputType = sharedPreferences.getInt(getString(R.string.location_type),0)

        //Initialising the recycler view, layout manager and using them
        recyclerView = binding.stateSelectorRecyclerView
        layoutManager = LinearLayoutManager(this.activity)
        recyclerView.layoutManager = layoutManager

        //Initialising the adapter for state selection
        //Defining click listener for the item
        val adapter = StateSelectorAdapter(StateSelectorListener {

            //Updating the state in the viewmodel
            activityViewModel.state = it.state

            //Going to the concerned city selector on selection of a state
            this.findNavController().navigate(StateSelectorFragmentDirections.actionStateSelectorFragmentToCitySelectorFragment(
                it.cities.toTypedArray()
            ))
        })

        //Setting the above adapter to the recycler view
        recyclerView.adapter = adapter

        //Submitting the list to the adapter of the states
        if (inputType == 0) {
            adapter.submitList(locationListSearch)
        } else {
            adapter.submitList(locationList)
        }

        return binding.root
    }

    //Lists for cities of the states for new pet

    private val andamanAndNicobarIslands = listOf(
        "Bakulatala",
        "Bambooflat",
        "Car Nicobar",
        "Diglipur",
        "Garacharma",
        "Hut Bay",
        "Kamorta",
        "Malacca",
        "Mayabunder",
        "Port Blair",
        "Prothrapur",
        "Rangat",
        "Tarasa Island"
    )

    private val andhraPradeshCities = listOf(
        "Adoni",
        "Anantapuram",
        "Bhimavaram",
        "Chilakaluripet",
        "Chittoor",
        "Dharmavaram",
        "Eluru",
        "Gudivada",
        "Guntakal",
        "Guntur",
        "Hindupur",
        "Kadapa",
        "Kakinada",
        "Kurnool",
        "Machilipatnam",
        "Madanapalle",
        "Mangalagiri",
        "Nandyal",
        "Narasaraopet",
        "Nellore",
        "Ongole",
        "Proddatur",
        "Rajahmahendravaram",
        "Srikakulam",
        "Tadepalligudem",
        "Tadipatri",
        "Tenali",
        "Tirupati",
        "Vijayawada",
        "Visakhapatnam",
        "Vizianagaram"
    )

    private val arunachalPradeshCities = listOf(
        "Anjaw",
        "Changlang",
        "East Siang",
        "Kurung Kumey",
        "Lohit",
        "Lower Dibang Valley",
        "Lower Subansiri",
        "Papum Pare",
        "Tawang",
        "Tirap",
        "Dibang Valley",
        "Upper Siang",
        "Upper Subansiri",
        "West Kameng",
        "West Siang"
    )

    private val assamCities = listOf(
        "Baksa",
        "Barpeta",
        "Bongaigaon",
        "Cachar",
        "Chirang",
        "Darrang",
        "Dhemaji",
        "Dima Hasao",
        "Dhubri",
        "Dibrugarh",
        "Goalpara",
        "Golaghat",
        "Hailakandi",
        "Jorhat",
        "Kamrup",
        "Kamrup Metropolitan",
        "Karbi Anglong",
        "Karimganj",
        "Kokrajhar",
        "Lakhimpur",
        "Marigaon",
        "Nagaon",
        "Nalbari",
        "Sibsagar",
        "Sonitpur",
        "Tinsukia",
        "Udalguri"
    )

    private val biharCities = listOf(
        "Araria",
        "Arwal",
        "Aurangabad",
        "Banka",
        "Begusarai",
        "Bhagalpur",
        "Bhojpur",
        "Buxar",
        "Darbhanga",
        "East Champaran",
        "Gaya",
        "Gopalganj",
        "Jamui",
        "Jehanabad",
        "Kaimur",
        "Katihar",
        "Khagaria",
        "Kishanganj",
        "Lakhisarai",
        "Madhepura",
        "Madhubani",
        "Munger",
        "Muzaffarpur",
        "Nalanda",
        "Nawada",
        "Patna",
        "Purnia",
        "Rohtas",
        "Saharsa",
        "Samastipur",
        "Saran",
        "Sheikhpura",
        "Sheohar",
        "Sitamarhi",
        "Siwan",
        "Supaul",
        "Vaishali",
        "West Champaran"
    )

    private val chandigarh = listOf(
        "Chandigarh"
    )

    private val chattisgarhCities = listOf(
        "Bastar",
        "Bijapur",
        "Bilaspur",
        "Dantewada",
        "Dhamtari",
        "Durg",
        "Jashpur",
        "Janjgir-Champa",
        "Korba",
        "Koriya",
        "Kanker",
        "Kabirdham",
        "Mahasamund",
        "Narayanpur",
        "Raigarh",
        "Rajnandgaon",
        "Raipur",
        "Surguja",
    )

    private val dadraAndNagarHaveli = listOf(
        "Alok City",
        "Dadra",
        "Dungra",
        "Masat Industrial Area",
        "Naroli",
        "Silvassa"
    )

    private val damanAndDiu = listOf(
        "Dadhel",
        "Daman",
        "Diu",
        "Ghoghla",
        "Kachigam"
    )

    private val delhi = listOf(
        "Alipur",
        "Chanakyapuri",
        "Civil Lines",
        "Daryaganj",
        "Defence Colony",
        "Delhi Cantonment",
        "Delhi NCR",
        "Dwarka",
        "Gandhi Nagar",
        "Hauz Khas",
        "Jamnagar House",
        "Kalkaji",
        "Kanjhawala",
        "Kapashera",
        "Karawal Nagar",
        "Karol Bagh",
        "Kotwali",
        "Mayur Vihar",
        "Mehrauli",
        "Model Town",
        "Najafgarh",
        "Nand Nagri",
        "Narela",
        "Patel Nagar",
        "Preet Vihar",
        "Punjabi Bagh",
        "Rajouri Garden",
        "Rohini",
        "Saket",
        "Saraswati Vihar",
        "Sarita Vihar",
        "Seelampur",
        "Seemapuri",
        "Shahdara",
        "Shastri Nagar",
        "Vasant Vihar",
        "Vivek Vihar",
        "Yamuna Vihar",
    )

    private val goaCities = listOf(
        "North Goa",
        "South Goa"
    )

    private val gujaratCities = listOf(
        "Ahmedabad",
        "Amreli district",
        "Anand",
        "Banaskantha",
        "Bharuch",
        "Bhavnagar",
        "Dahod",
        "The Dangs",
        "Gandhinagar",
        "Jamnagar",
        "Junagadh",
        "Kutch",
        "Kheda",
        "Mehsana",
        "Narmada",
        "Navsari",
        "Patan",
        "Panchmahal",
        "Porbandar",
        "Rajkot",
        "Sabarkantha",
        "Surendranagar",
        "Surat",
        "Vyara",
        "Vadodara",
        "Valsad",
    )

    private val haryanaCities = listOf(
        "Ambala",
        "Bhiwani",
        "Faridabad",
        "Fatehabad",
        "Gurugram",
        "Hissar",
        "Jhajjar",
        "Jind",
        "Karnal",
        "Kaithal",
        "Kurukshetra",
        "Mahendragarh",
        "Mewat",
        "Palwal",
        "Panchkula",
        "Panipat",
        "Rewari",
        "Rohtak",
        "Sirsa",
        "Sonipat",
        "Yamuna Nagar",
    )

    private val himachalPradeshCities = listOf(
        "Bilaspur",
        "Chamba",
        "Hamirpur",
        "Kangra",
        "Kinnaur",
        "Kullu",
        "Lahaul Spiti",
        "Mandi",
        "Shimla",
        "Sirmaur",
        "Solan",
        "Una",
    )

    private val jammuAndKashmir = listOf(
        "Anantnag",
        "Badgam",
        "Bandipora",
        "Baramulla",
        "Doda",
        "Ganderbal",
        "Jammu",
        "Kargil",
        "Kathua",
        "Kishtwar",
        "Kupwara",
        "Kulgam",
        "Leh",
        "Poonch",
        "Pulwama",
        "Rajauri",
        "Ramban",
        "Reasi",
        "Samba",
        "Shopian",
        "Srinagar",
        "Udhampur"
    )

    private val jharkhandCities = listOf(
        "Bokaro",
        "Chatra",
        "Deoghar",
        "Dhanbad",
        "Dumka",
        "East Singhbhum",
        "Garhwa",
        "Giridih",
        "Godda",
        "Gumla",
        "Hazaribag",
        "Jamtara",
        "Khunti",
        "Koderma",
        "Latehar",
        "Lohardaga",
        "Pakur",
        "Palamu",
        "Ramgarh",
        "Ranchi",
        "Sahibganj",
        "Seraikela Kharsawan",
        "Simdega",
        "West Singhbhum",
    )

    private val karnatakaCities = listOf(
        "Bagalkot",
        "Bangalore Rural",
        "Bangalore Urban",
        "Belgaum",
        "Bellary",
        "Bidar",
        "Bijapur",
        "Chamarajnagar",
        "Chikkamagaluru",
        "Chikkaballapur",
        "Chitradurga",
        "Davanagere",
        "Dharwad",
        "Dakshina Kannada",
        "Gadag",
        "Gulbarga",
        "Hassan",
        "Haveri district",
        "Kodagu",
        "Kolar",
        "Koppal",
        "Mandya",
        "Mysore",
        "Raichur",
        "Shimoga",
        "Tumkur",
        "Udupi",
        "Uttara Kannada",
        "Ramanagara",
        "Yadgir",
    )

    private val keralaCities = listOf(
        "Alappuzha",
        "Ernakulam",
        "Idukki",
        "Kannur",
        "Kasaragod",
        "Kollam",
        "Kottayam",
        "Kozhikode",
        "Malappuram",
        "Palakkad",
        "Pathanamthitta",
        "Thrissur",
        "Thiruvananthapuram",
        "Wayanad",
    )

    private val lakshadweep = listOf(
        "Agatti",
        "Amini",
        "Andrott",
        "Bangaram",
        "Bitra",
        "Chetlat",
        "Kadmat",
        "Kalpeni",
        "Kavaratti",
        "Kiltan",
        "Minicoy"
    )

    private val madhyaPradeshCities = listOf(
        "Alirajpur",
        "Anuppur",
        "Ashok Nagar",
        "Balaghat",
        "Barwani",
        "Betul",
        "Bhind",
        "Bhopal",
        "Burhanpur",
        "Chhatarpur",
        "Chhindwara",
        "Damoh",
        "Datia",
        "Dewas",
        "Dhar",
        "Dindori",
        "Guna",
        "Gwalior",
        "Harda",
        "Hoshangabad",
        "Indore",
        "Jabalpur",
        "Jhabua",
        "Katni",
        "Khandwa",
        "Khargone",
        "Mandla",
        "Mandsaur",
        "Morena",
        "Narsinghpur",
        "Neemuch",
        "Panna",
        "Rewa",
        "Rajgarh",
        "Ratlam",
        "Raisen",
        "Sagar",
        "Satna",
        "Sehore",
        "Seoni",
        "Shahdol",
        "Shajapur",
        "Sheopur",
        "Shivpuri",
        "Sidhi",
        "Singrauli",
        "Tikamgarh",
        "Ujjain",
        "Umaria",
        "Vidisha",
    )

    private val maharashtraCities = listOf(
        "Ahmednagar",
        "Akola",
        "Amravati",
        "Aurangabad",
        "Bhandara",
        "Beed",
        "Buldhana",
        "Chandrapur",
        "Dhule",
        "Gadchiroli",
        "Gondia",
        "Hingoli",
        "Jalgaon",
        "Jalna",
        "Kolhapur",
        "Latur",
        "Mumbai City",
        "Mumbai suburban",
        "Nandurbar",
        "Nanded",
        "Nagpur",
        "Nashik",
        "Osmanabad",
        "Parbhani",
        "Pune",
        "Raigad",
        "Ratnagiri",
        "Sindhudurg",
        "Sangli",
        "Solapur",
        "Satara",
        "Thane",
        "Wardha",
        "Washim",
        "Yavatmal"
    )

    private val manipurCities = listOf(
        "Bishnupur",
        "Churachandpur",
        "Chandel",
        "Imphal East",
        "Senapati",
        "Tamenglong",
        "Thoubal",
        "Ukhrul",
        "Imphal West"
    )

    private val meghalayaCities = listOf(
        "East Garo Hills",
        "East Khasi Hills",
        "Jaintia Hills",
        "Ri Bhoi",
        "South Garo Hills",
        "West Garo Hills",
        "West Khasi Hills"
    )

    private val mizoramCities = listOf(
        "Aizawl",
        "Champhai",
        "Kolasib",
        "Lawngtlai",
        "Lunglei",
        "Mamit",
        "Saiha",
        "Serchhip"
    )

    private val nagalandCities = listOf(
        "Dimapur",
        "Kohima",
        "Mokokchung",
        "Mon",
        "Phek",
        "Tuensang",
        "Wokha",
        "Zunheboto"
    )

    private val odishaCities = listOf(
        "Angul",
        "Boudh",
        "Bhadrak",
        "Balangir",
        "Baragarh",
        "Balasore",
        "Cuttack",
        "Deogarh",
        "Dhenkanal",
        "Ganjam",
        "Gajapati",
        "Jharsuguda",
        "Jajpur",
        "Jagatsinghpur",
        "Khordha",
        "Kendujhar",
        "Kalahandi",
        "Kandhamal",
        "Koraput",
        "Kendrapara",
        "Malkangiri",
        "Mayurbhanj",
        "Nabarangpur",
        "Nuapada",
        "Nayagarh",
        "Puri",
        "Rayagada",
        "Sambalpur",
        "Sonepur",
        "Sundergarh"
    )

    private val pondicherry = listOf(
        "Anna Nagar",
        "Karaikal",
        "Mahe",
        "Oulgaret",
        "Puducherry",
        "Reddiarpalayam",
        "Thirumalairayan Pattinam",
        "Yanam"
    )

    private val punjabCities = listOf(
        "Amritsar",
        "Barnala",
        "Bathinda",
        "Firozpur",
        "Faridkot",
        "Fatehgarh Sahib",
        "Fazilka",
        "Gurdaspur",
        "Hoshiarpur",
        "Jalandhar",
        "Kapurthala",
        "Ludhiana",
        "Mansa",
        "Moga",
        "Sri Muktsar Sahib",
        "Pathankot",
        "Patiala",
        "Rupnagar",
        "Mohali",
        "Sangrur",
        "Nawanshahr",
        "Tarn Taran"
    )

    private val rajasthanCities = listOf(
        "Ajmer",
        "Alwar",
        "Bikaner",
        "Barmer",
        "Banswara",
        "Bharatpur",
        "Baran",
        "Bundi",
        "Bhilwara",
        "Churu",
        "Chittorgarh",
        "Dausa",
        "Dholpur",
        "Dungapur",
        "Ganganagar",
        "Hanumangarh",
        "Jhunjhunu",
        "Jalore",
        "Jodhpur",
        "Jaipur",
        "Jaisalmer",
        "Jhalawar",
        "Karauli",
        "Kota",
        "Nagaur",
        "Pali",
        "Pratapgarh",
        "Rajsamand",
        "Sikar",
        "Sawai Madhopur",
        "Sirohi",
        "Tonk",
        "Udaipur"
    )

    private val sikkimCities = listOf(
        "East Sikkim",
        "North Sikkim",
        "South Sikkim",
        "West Sikkim"
    )

    private val tamilNaduCities = listOf(
        "Ariyalur",
        "Chennai",
        "Coimbatore",
        "Cuddalore",
        "Dharmapuri",
        "Dindigul",
        "Erode",
        "Kanchipuram",
        "Kanyakumari",
        "Karur",
        "Madurai",
        "Nagapattinam",
        "Nilgiris",
        "Namakkal",
        "Perambalur",
        "Pudukkottai",
        "Ramanathapuram",
        "Salem",
        "Sivaganga",
        "Tirupur",
        "Tiruchirappalli",
        "Theni",
        "Tirunelveli",
        "Thanjavur",
        "Thoothukudi",
        "Tiruvallur",
        "Tiruvarur",
        "Tiruvannamalai",
        "Vellore",
        "Viluppuram",
        "Virudhunagar"
    )

    private val telanganaCities = listOf(
        "Adilabad",
        "Hyderabad",
        "Jagtial",
        "Karimnagar",
        "Khammam",
        "Mahabubnagar",
        "Miryalaguda",
        "Nalgonda",
        "Nizamabad",
        "Ramagundam",
        "Siddpet",
        "Suryapet",
        "Warangal"
    )

    private val tripuracities = listOf(
        "Dhalai",
        "North Tripura",
        "South Tripura",
        "Khowai",
        "West Tripura"
    )

    private val upCities = listOf(
        "Agra",
        "Allahabad",
        "Aligarh",
        "Ambedkar Nagar",
        "Auraiya",
        "Azamgarh",
        "Barabanki",
        "Budaun",
        "Bagpat",
        "Bahraich",
        "Bijnor",
        "Ballia",
        "Banda",
        "Balrampur",
        "Bareilly",
        "Basti",
        "Bulandshahr",
        "Chandauli",
        "Chhatrapati Shahuji Maharaj Nagar",
        "Chitrakoot",
        "Deoria",
        "Etah",
        "Kanshi Ram Nagar",
        "Etawah",
        "Firozabad",
        "Farrukhabad",
        "Fatehpur",
        "Faizabad",
        "Gautam Buddh Nagar",
        "Gonda",
        "Ghazipur",
        "Gorakhpur",
        "Ghaziabad",
        "Hamirpur",
        "Hardoi",
        "Mahamaya Nagar",
        "Jhansi",
        "Jalaun",
        "Jyotiba Phule Nagar",
        "Jaunpur district",
        "Ramabai Nagar",
        "Kannauj",
        "Kanpur",
        "Kaushambi",
        "Kushinagar",
        "Lalitpur",
        "Lakhimpur Kheri",
        "Lucknow",
        "Mau",
        "Meerut",
        "Maharajganj",
        "Mahoba",
        "Mirzapur",
        "Moradabad",
        "Mainpuri",
        "Mathura",
        "Muzaffarnagar",
        "Hapur",
        "Pilibhit",
        "Shamli",
        "Pratapgarh",
        "Rampur",
        "Raebareli",
        "Saharanpur",
        "Sitapur",
        "Shahjahanpur",
        "Sant Kabir Nagar",
        "Siddharthnagar",
        "Sonbhadra",
        "Sant Ravidas Nagar",
        "Sultanpur",
        "Shravasti",
        "Unnao",
        "Varanasi"
    )

    private val uttarakhandCities = listOf(
        "Almora",
        "Bageshwar",
        "Chamoli",
        "Champawat",
        "Dehradun",
        "Haridwar",
        "Nainital",
        "Pauri Garhwal",
        "Pithoragarh",
        "Rudraprayag",
        "Tehri Garhwal",
        "Udham Singh Nagar",
        "Uttarkashi"
    )

    private val westBengalCities = listOf(
        "Birbhum",
        "Bankura",
        "Bardhaman",
        "Darjeeling",
        "Dakshin Dinajpur",
        "Hooghly",
        "Howrah",
        "Jalpaiguri",
        "Cooch Behar",
        "Kolkata",
        "Maldah",
        "Paschim Medinipur",
        "Purba Medinipur",
        "Murshidabad",
        "Nadia",
        "North 24 Parganas",
        "South 24 Parganas",
        "Purulia",
        "Uttar Dinajpur"
    )

    //List of the location objects with state and its list of cities
    private val locationList = listOf(
        Location("Andaman & Nicobar Islands",andamanAndNicobarIslands),
        Location("Andhra Pradesh",andhraPradeshCities),
        Location("Arunachal Pradesh",arunachalPradeshCities),
        Location("Assam",assamCities),
        Location("Bihar",biharCities),
        Location("Chandigarh",chandigarh),
        Location("Chattisgarh",chattisgarhCities),
        Location("Dadra & Nagar Haveli",dadraAndNagarHaveli),
        Location("Daman & Diu",damanAndDiu),
        Location("Delhi",delhi),
        Location("Goa",goaCities),
        Location("Gujarat",gujaratCities),
        Location("Haryana",haryanaCities),
        Location("Himachal Pradesh",himachalPradeshCities),
        Location("Jammu & Kashmir",jammuAndKashmir),
        Location("Jharkhand",jharkhandCities),
        Location("Karnataka",karnatakaCities),
        Location("Kerala",keralaCities),
        Location("Lakshadweep",lakshadweep),
        Location("Madhya Pradesh",madhyaPradeshCities),
        Location("Maharashtra",maharashtraCities),
        Location("Manipur",manipurCities),
        Location("Meghalaya",meghalayaCities),
        Location("Mizoram",mizoramCities),
        Location("Nagaland",nagalandCities),
        Location("Odisha",odishaCities),
        Location("Pondicherry",pondicherry),
        Location("Punjab",punjabCities),
        Location("Rajasthan",rajasthanCities),
        Location("Sikkim",sikkimCities),
        Location("Tamil Nadu",tamilNaduCities),
        Location("Telangana",telanganaCities),
        Location("Tripura",tripuracities),
        Location("Uttar Pradesh",upCities),
        Location("Uttarakhand",uttarakhandCities),
        Location("West Bengal",westBengalCities)
    )


    //Lists for cities of the states for search

    private val andamanAndNicobarIslandsSearch = listOf(
        "All in Andaman & Nicobar",
        "Bakulatala",
        "Bambooflat",
        "Car Nicobar",
        "Diglipur",
        "Garacharma",
        "Hut Bay",
        "Kamorta",
        "Malacca",
        "Mayabunder",
        "Port Blair",
        "Prothrapur",
        "Rangat",
        "Tarasa Island"
    )

    private val andhraPradeshCitiesSearch = listOf(
        "All in Andhra Pradesh",
        "Adoni",
        "Anantapuram",
        "Bhimavaram",
        "Chilakaluripet",
        "Chittoor",
        "Dharmavaram",
        "Eluru",
        "Gudivada",
        "Guntakal",
        "Guntur",
        "Hindupur",
        "Kadapa",
        "Kakinada",
        "Kurnool",
        "Machilipatnam",
        "Madanapalle",
        "Mangalagiri",
        "Nandyal",
        "Narasaraopet",
        "Nellore",
        "Ongole",
        "Proddatur",
        "Rajahmahendravaram",
        "Srikakulam",
        "Tadepalligudem",
        "Tadipatri",
        "Tenali",
        "Tirupati",
        "Vijayawada",
        "Visakhapatnam",
        "Vizianagaram"
    )

    private val arunachalPradeshCitiesSearch = listOf(
        "All in Arunachal Pradesh",
        "Anjaw",
        "Changlang",
        "East Siang",
        "Kurung Kumey",
        "Lohit",
        "Lower Dibang Valley",
        "Lower Subansiri",
        "Papum Pare",
        "Tawang",
        "Tirap",
        "Dibang Valley",
        "Upper Siang",
        "Upper Subansiri",
        "West Kameng",
        "West Siang"
    )

    private val assamCitiesSearch = listOf(
        "All in Assam",
        "Baksa",
        "Barpeta",
        "Bongaigaon",
        "Cachar",
        "Chirang",
        "Darrang",
        "Dhemaji",
        "Dima Hasao",
        "Dhubri",
        "Dibrugarh",
        "Goalpara",
        "Golaghat",
        "Hailakandi",
        "Jorhat",
        "Kamrup",
        "Kamrup Metropolitan",
        "Karbi Anglong",
        "Karimganj",
        "Kokrajhar",
        "Lakhimpur",
        "Marigaon",
        "Nagaon",
        "Nalbari",
        "Sibsagar",
        "Sonitpur",
        "Tinsukia",
        "Udalguri"
    )

    private val biharCitiesSearch = listOf(
        "All in Bihar",
        "Araria",
        "Arwal",
        "Aurangabad",
        "Banka",
        "Begusarai",
        "Bhagalpur",
        "Bhojpur",
        "Buxar",
        "Darbhanga",
        "East Champaran",
        "Gaya",
        "Gopalganj",
        "Jamui",
        "Jehanabad",
        "Kaimur",
        "Katihar",
        "Khagaria",
        "Kishanganj",
        "Lakhisarai",
        "Madhepura",
        "Madhubani",
        "Munger",
        "Muzaffarpur",
        "Nalanda",
        "Nawada",
        "Patna",
        "Purnia",
        "Rohtas",
        "Saharsa",
        "Samastipur",
        "Saran",
        "Sheikhpura",
        "Sheohar",
        "Sitamarhi",
        "Siwan",
        "Supaul",
        "Vaishali",
        "West Champaran"
    )

    private val chandigarhSearch = listOf(
        "Chandigarh"
    )

    private val chattisgarhCitiesSearch = listOf(
        "All in Chattisgarh",
        "Bastar",
        "Bijapur",
        "Bilaspur",
        "Dantewada",
        "Dhamtari",
        "Durg",
        "Jashpur",
        "Janjgir-Champa",
        "Korba",
        "Koriya",
        "Kanker",
        "Kabirdham",
        "Mahasamund",
        "Narayanpur",
        "Raigarh",
        "Rajnandgaon",
        "Raipur",
        "Surguja",
    )

    private val dadraAndNagarHaveliSearch = listOf(
        "All in Dadra & Nagar haveli",
        "Alok City",
        "Dadra",
        "Dungra",
        "Masat Industrial Area",
        "Naroli",
        "Silvassa"
    )

    private val damanAndDiuSearch = listOf(
        "All in Daman & Diu",
        "Dadhel",
        "Daman",
        "Diu",
        "Ghoghla",
        "Kachigam"
    )

    private val delhiSearch = listOf(
        "All in Delhi",
        "Alipur",
        "Chanakyapuri",
        "Civil Lines",
        "Daryaganj",
        "Defence Colony",
        "Delhi Cantonment",
        "Delhi NCR",
        "Dwarka",
        "Gandhi Nagar",
        "Hauz Khas",
        "Jamnagar House",
        "Kalkaji",
        "Kanjhawala",
        "Kapashera",
        "Karawal Nagar",
        "Karol Bagh",
        "Kotwali",
        "Mayur Vihar",
        "Mehrauli",
        "Model Town",
        "Najafgarh",
        "Nand Nagri",
        "Narela",
        "Patel Nagar",
        "Preet Vihar",
        "Punjabi Bagh",
        "Rajouri Garden",
        "Rohini",
        "Saket",
        "Saraswati Vihar",
        "Sarita Vihar",
        "Seelampur",
        "Seemapuri",
        "Shahdara",
        "Shastri Nagar",
        "Vasant Vihar",
        "Vivek Vihar",
        "Yamuna Vihar",
    )

    private val goaCitiesSearch = listOf(
        "All in Goa",
        "North Goa",
        "South Goa"
    )

    private val gujaratCitiesSearch = listOf(
        "All in Gujarat",
        "Ahmedabad",
        "Amreli district",
        "Anand",
        "Banaskantha",
        "Bharuch",
        "Bhavnagar",
        "Dahod",
        "The Dangs",
        "Gandhinagar",
        "Jamnagar",
        "Junagadh",
        "Kutch",
        "Kheda",
        "Mehsana",
        "Narmada",
        "Navsari",
        "Patan",
        "Panchmahal",
        "Porbandar",
        "Rajkot",
        "Sabarkantha",
        "Surendranagar",
        "Surat",
        "Vyara",
        "Vadodara",
        "Valsad",
    )

    private val haryanaCitiesSearch = listOf(
        "All in Haryana",
        "Ambala",
        "Bhiwani",
        "Faridabad",
        "Fatehabad",
        "Gurugram",
        "Hissar",
        "Jhajjar",
        "Jind",
        "Karnal",
        "Kaithal",
        "Kurukshetra",
        "Mahendragarh",
        "Mewat",
        "Palwal",
        "Panchkula",
        "Panipat",
        "Rewari",
        "Rohtak",
        "Sirsa",
        "Sonipat",
        "Yamuna Nagar",
    )

    private val himachalPradeshCitiesSearch = listOf(
        "All in Himachal Pradesh",
        "Bilaspur",
        "Chamba",
        "Hamirpur",
        "Kangra",
        "Kinnaur",
        "Kullu",
        "Lahaul Spiti",
        "Mandi",
        "Shimla",
        "Sirmaur",
        "Solan",
        "Una",
    )

    private val jammuAndKashmirSearch = listOf(
        "All in Jammu & Kashmir",
        "Anantnag",
        "Badgam",
        "Bandipora",
        "Baramulla",
        "Doda",
        "Ganderbal",
        "Jammu",
        "Kargil",
        "Kathua",
        "Kishtwar",
        "Kupwara",
        "Kulgam",
        "Leh",
        "Poonch",
        "Pulwama",
        "Rajauri",
        "Ramban",
        "Reasi",
        "Samba",
        "Shopian",
        "Srinagar",
        "Udhampur"
    )

    private val jharkhandCitiesSearch = listOf(
        "All in Jharkhand",
        "Bokaro",
        "Chatra",
        "Deoghar",
        "Dhanbad",
        "Dumka",
        "East Singhbhum",
        "Garhwa",
        "Giridih",
        "Godda",
        "Gumla",
        "Hazaribag",
        "Jamtara",
        "Khunti",
        "Koderma",
        "Latehar",
        "Lohardaga",
        "Pakur",
        "Palamu",
        "Ramgarh",
        "Ranchi",
        "Sahibganj",
        "Seraikela Kharsawan",
        "Simdega",
        "West Singhbhum",
    )

    private val karnatakaCitiesSearch = listOf(
        "All in Karnataka",
        "Bagalkot",
        "Bangalore Rural",
        "Bangalore Urban",
        "Belgaum",
        "Bellary",
        "Bidar",
        "Bijapur",
        "Chamarajnagar",
        "Chikkamagaluru",
        "Chikkaballapur",
        "Chitradurga",
        "Davanagere",
        "Dharwad",
        "Dakshina Kannada",
        "Gadag",
        "Gulbarga",
        "Hassan",
        "Haveri district",
        "Kodagu",
        "Kolar",
        "Koppal",
        "Mandya",
        "Mysore",
        "Raichur",
        "Shimoga",
        "Tumkur",
        "Udupi",
        "Uttara Kannada",
        "Ramanagara",
        "Yadgir",
    )

    private val keralaCitiesSearch = listOf(
        "All in Kerala",
        "Alappuzha",
        "Ernakulam",
        "Idukki",
        "Kannur",
        "Kasaragod",
        "Kollam",
        "Kottayam",
        "Kozhikode",
        "Malappuram",
        "Palakkad",
        "Pathanamthitta",
        "Thrissur",
        "Thiruvananthapuram",
        "Wayanad",
    )

    private val lakshadweepSearch = listOf(
        "All in Lakshadweep",
        "Agatti",
        "Amini",
        "Andrott",
        "Bangaram",
        "Bitra",
        "Chetlat",
        "Kadmat",
        "Kalpeni",
        "Kavaratti",
        "Kiltan",
        "Minicoy"
    )

    private val madhyaPradeshCitiesSearch = listOf(
        "All in Madhya Pradesh",
        "Alirajpur",
        "Anuppur",
        "Ashok Nagar",
        "Balaghat",
        "Barwani",
        "Betul",
        "Bhind",
        "Bhopal",
        "Burhanpur",
        "Chhatarpur",
        "Chhindwara",
        "Damoh",
        "Datia",
        "Dewas",
        "Dhar",
        "Dindori",
        "Guna",
        "Gwalior",
        "Harda",
        "Hoshangabad",
        "Indore",
        "Jabalpur",
        "Jhabua",
        "Katni",
        "Khandwa",
        "Khargone",
        "Mandla",
        "Mandsaur",
        "Morena",
        "Narsinghpur",
        "Neemuch",
        "Panna",
        "Rewa",
        "Rajgarh",
        "Ratlam",
        "Raisen",
        "Sagar",
        "Satna",
        "Sehore",
        "Seoni",
        "Shahdol",
        "Shajapur",
        "Sheopur",
        "Shivpuri",
        "Sidhi",
        "Singrauli",
        "Tikamgarh",
        "Ujjain",
        "Umaria",
        "Vidisha",
    )

    private val maharashtraCitiesSearch = listOf(
        "All in Maharashtra",
        "Ahmednagar",
        "Akola",
        "Amravati",
        "Aurangabad",
        "Bhandara",
        "Beed",
        "Buldhana",
        "Chandrapur",
        "Dhule",
        "Gadchiroli",
        "Gondia",
        "Hingoli",
        "Jalgaon",
        "Jalna",
        "Kolhapur",
        "Latur",
        "Mumbai City",
        "Mumbai suburban",
        "Nandurbar",
        "Nanded",
        "Nagpur",
        "Nashik",
        "Osmanabad",
        "Parbhani",
        "Pune",
        "Raigad",
        "Ratnagiri",
        "Sindhudurg",
        "Sangli",
        "Solapur",
        "Satara",
        "Thane",
        "Wardha",
        "Washim",
        "Yavatmal"
    )

    private val manipurCitiesSearch = listOf(
        "All in Manipur",
        "Bishnupur",
        "Churachandpur",
        "Chandel",
        "Imphal East",
        "Senapati",
        "Tamenglong",
        "Thoubal",
        "Ukhrul",
        "Imphal West"
    )

    private val meghalayaCitiesSearch = listOf(
        "All in Meghalaya",
        "East Garo Hills",
        "East Khasi Hills",
        "Jaintia Hills",
        "Ri Bhoi",
        "South Garo Hills",
        "West Garo Hills",
        "West Khasi Hills"
    )

    private val mizoramCitiesSearch = listOf(
        "All in Mizoram",
        "Aizawl",
        "Champhai",
        "Kolasib",
        "Lawngtlai",
        "Lunglei",
        "Mamit",
        "Saiha",
        "Serchhip"
    )

    private val nagalandCitiesSearch = listOf(
        "All in Nagaland",
        "Dimapur",
        "Kohima",
        "Mokokchung",
        "Mon",
        "Phek",
        "Tuensang",
        "Wokha",
        "Zunheboto"
    )

    private val odishaCitiesSearch = listOf(
        "All in Odisha",
        "Angul",
        "Boudh",
        "Bhadrak",
        "Balangir",
        "Baragarh",
        "Balasore",
        "Cuttack",
        "Deogarh",
        "Dhenkanal",
        "Ganjam",
        "Gajapati",
        "Jharsuguda",
        "Jajpur",
        "Jagatsinghpur",
        "Khordha",
        "Kendujhar",
        "Kalahandi",
        "Kandhamal",
        "Koraput",
        "Kendrapara",
        "Malkangiri",
        "Mayurbhanj",
        "Nabarangpur",
        "Nuapada",
        "Nayagarh",
        "Puri",
        "Rayagada",
        "Sambalpur",
        "Sonepur",
        "Sundergarh"
    )

    private val pondicherrySearch = listOf(
        "All in Pondicherry",
        "Anna Nagar",
        "Karaikal",
        "Mahe",
        "Oulgaret",
        "Puducherry",
        "Reddiarpalayam",
        "Thirumalairayan Pattinam",
        "Yanam"
    )

    private val punjabCitiesSearch = listOf(
        "All in Punjab",
        "Amritsar",
        "Barnala",
        "Bathinda",
        "Firozpur",
        "Faridkot",
        "Fatehgarh Sahib",
        "Fazilka",
        "Gurdaspur",
        "Hoshiarpur",
        "Jalandhar",
        "Kapurthala",
        "Ludhiana",
        "Mansa",
        "Moga",
        "Sri Muktsar Sahib",
        "Pathankot",
        "Patiala",
        "Rupnagar",
        "Mohali",
        "Sangrur",
        "Nawanshahr",
        "Tarn Taran"
    )

    private val rajasthanCitiesSearch = listOf(
        "All in Rajasthan",
        "Ajmer",
        "Alwar",
        "Bikaner",
        "Barmer",
        "Banswara",
        "Bharatpur",
        "Baran",
        "Bundi",
        "Bhilwara",
        "Churu",
        "Chittorgarh",
        "Dausa",
        "Dholpur",
        "Dungapur",
        "Ganganagar",
        "Hanumangarh",
        "Jhunjhunu",
        "Jalore",
        "Jodhpur",
        "Jaipur",
        "Jaisalmer",
        "Jhalawar",
        "Karauli",
        "Kota",
        "Nagaur",
        "Pali",
        "Pratapgarh",
        "Rajsamand",
        "Sikar",
        "Sawai Madhopur",
        "Sirohi",
        "Tonk",
        "Udaipur"
    )

    private val sikkimCitiesSearch = listOf(
        "All in Sikkim",
        "East Sikkim",
        "North Sikkim",
        "South Sikkim",
        "West Sikkim"
    )

    private val tamilNaduCitiesSearch = listOf(
        "All in Tamil Nadu",
        "Ariyalur",
        "Chennai",
        "Coimbatore",
        "Cuddalore",
        "Dharmapuri",
        "Dindigul",
        "Erode",
        "Kanchipuram",
        "Kanyakumari",
        "Karur",
        "Madurai",
        "Nagapattinam",
        "Nilgiris",
        "Namakkal",
        "Perambalur",
        "Pudukkottai",
        "Ramanathapuram",
        "Salem",
        "Sivaganga",
        "Tirupur",
        "Tiruchirappalli",
        "Theni",
        "Tirunelveli",
        "Thanjavur",
        "Thoothukudi",
        "Tiruvallur",
        "Tiruvarur",
        "Tiruvannamalai",
        "Vellore",
        "Viluppuram",
        "Virudhunagar"
    )

    private val telanganaCitiesSearch = listOf(
        "All in Telangana",
        "Adilabad",
        "Hyderabad",
        "Jagtial",
        "Karimnagar",
        "Khammam",
        "Mahabubnagar",
        "Miryalaguda",
        "Nalgonda",
        "Nizamabad",
        "Ramagundam",
        "Siddpet",
        "Suryapet",
        "Warangal"
    )

    private val tripuracitiesSearch = listOf(
        "All in Tripura",
        "Dhalai",
        "North Tripura",
        "South Tripura",
        "Khowai",
        "West Tripura"
    )

    private val upCitiesSearch = listOf(
        "All in Uttar Pradesh",
        "Agra",
        "Allahabad",
        "Aligarh",
        "Ambedkar Nagar",
        "Auraiya",
        "Azamgarh",
        "Barabanki",
        "Budaun",
        "Bagpat",
        "Bahraich",
        "Bijnor",
        "Ballia",
        "Banda",
        "Balrampur",
        "Bareilly",
        "Basti",
        "Bulandshahr",
        "Chandauli",
        "Chhatrapati Shahuji Maharaj Nagar",
        "Chitrakoot",
        "Deoria",
        "Etah",
        "Kanshi Ram Nagar",
        "Etawah",
        "Firozabad",
        "Farrukhabad",
        "Fatehpur",
        "Faizabad",
        "Gautam Buddh Nagar",
        "Gonda",
        "Ghazipur",
        "Gorakhpur",
        "Ghaziabad",
        "Hamirpur",
        "Hardoi",
        "Mahamaya Nagar",
        "Jhansi",
        "Jalaun",
        "Jyotiba Phule Nagar",
        "Jaunpur district",
        "Ramabai Nagar",
        "Kannauj",
        "Kanpur",
        "Kaushambi",
        "Kushinagar",
        "Lalitpur",
        "Lakhimpur Kheri",
        "Lucknow",
        "Mau",
        "Meerut",
        "Maharajganj",
        "Mahoba",
        "Mirzapur",
        "Moradabad",
        "Mainpuri",
        "Mathura",
        "Muzaffarnagar",
        "Hapur",
        "Pilibhit",
        "Shamli",
        "Pratapgarh",
        "Rampur",
        "Raebareli",
        "Saharanpur",
        "Sitapur",
        "Shahjahanpur",
        "Sant Kabir Nagar",
        "Siddharthnagar",
        "Sonbhadra",
        "Sant Ravidas Nagar",
        "Sultanpur",
        "Shravasti",
        "Unnao",
        "Varanasi"
    )

    private val uttarakhandCitiesSearch = listOf(
        "All in Uttarakhand",
        "Almora",
        "Bageshwar",
        "Chamoli",
        "Champawat",
        "Dehradun",
        "Haridwar",
        "Nainital",
        "Pauri Garhwal",
        "Pithoragarh",
        "Rudraprayag",
        "Tehri Garhwal",
        "Udham Singh Nagar",
        "Uttarkashi"
    )

    private val westBengalCitiesSearch = listOf(
        "All in West Bengal",
        "Birbhum",
        "Bankura",
        "Bardhaman",
        "Darjeeling",
        "Dakshin Dinajpur",
        "Hooghly",
        "Howrah",
        "Jalpaiguri",
        "Cooch Behar",
        "Kolkata",
        "Maldah",
        "Paschim Medinipur",
        "Purba Medinipur",
        "Murshidabad",
        "Nadia",
        "North 24 Parganas",
        "South 24 Parganas",
        "Purulia",
        "Uttar Dinajpur"
    )

    private val indiaSearch = listOf(
        "All in India"
    )

    //List of the location objects with state and its list of cities
    private val locationListSearch = listOf(
        Location("India",indiaSearch),
        Location("Andaman & Nicobar Islands",andamanAndNicobarIslandsSearch),
        Location("Andhra Pradesh",andhraPradeshCitiesSearch),
        Location("Arunachal Pradesh",arunachalPradeshCitiesSearch),
        Location("Assam",assamCitiesSearch),
        Location("Bihar",biharCitiesSearch),
        Location("Chandigarh",chandigarhSearch),
        Location("Chattisgarh",chattisgarhCitiesSearch),
        Location("Dadra & Nagar Haveli",dadraAndNagarHaveliSearch),
        Location("Daman & Diu",damanAndDiuSearch),
        Location("Delhi",delhiSearch),
        Location("Goa",goaCitiesSearch),
        Location("Gujarat",gujaratCitiesSearch),
        Location("Haryana",haryanaCitiesSearch),
        Location("Himachal Pradesh",himachalPradeshCitiesSearch),
        Location("Jammu & Kashmir",jammuAndKashmirSearch),
        Location("Jharkhand",jharkhandCitiesSearch),
        Location("Karnataka",karnatakaCitiesSearch),
        Location("Kerala",keralaCitiesSearch),
        Location("Lakshadweep",lakshadweepSearch),
        Location("Madhya Pradesh",madhyaPradeshCitiesSearch),
        Location("Maharashtra",maharashtraCitiesSearch),
        Location("Manipur",manipurCitiesSearch),
        Location("Meghalaya",meghalayaCitiesSearch),
        Location("Mizoram",mizoramCitiesSearch),
        Location("Nagaland",nagalandCitiesSearch),
        Location("Odisha",odishaCitiesSearch),
        Location("Pondicherry",pondicherrySearch),
        Location("Punjab",punjabCitiesSearch),
        Location("Rajasthan",rajasthanCitiesSearch),
        Location("Sikkim",sikkimCitiesSearch),
        Location("Tamil Nadu",tamilNaduCitiesSearch),
        Location("Telangana",telanganaCitiesSearch),
        Location("Tripura",tripuracitiesSearch),
        Location("Uttar Pradesh",upCitiesSearch),
        Location("Uttarakhand",uttarakhandCitiesSearch),
        Location("West Bengal",westBengalCitiesSearch)
    )

}